QDRANT_API_KEY = "Z-u_rs6zKpGDIgEvi0wyxoynj-j5pVj5njY4BrtdO29P7cFSPOtwHw"
QDRANT_URL="https://12cf1cc6-ae8b-4f0f-93fe-f887ae6a11ee.europe-west3-0.gcp.cloud.qdrant.io:6333"
GEMINI_API = "AIzaSyAgvirzRqyoUs1mumALilwhDtVmy19Xv6E"